name: Build and Publish OTBR Add-on

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [aarch64, amd64, armhf, armv7, i386]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: home-assistant/builder@2026.01.1
        with:
          args: |
            --${{ matrix.arch }} \
            --target openthread_border_router \
            --docker-hub ghcr.io/${{ github.repository_owner }}
